load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "variables_methods",
    srcs = ["variables_methods.cpp", "variables_methods.h"],
    #hdrs = ["variables_methods.h"],
    visibility = ["//main:__subpackages__"],
)